---
version: 0
os: linux
files:
  - source: Scripts/test.sh
    destination: /tmp/
  - source: post-scripts/test.sh
    destination: /tmp/post-scripts
hooks:
  BeforeInstall:
    - location: pre-scripts/checke.sh
  AfterInstall:
    - location: post-scripts/TestScript.sh
      timeout: 60
  ValidateService:
    - location: post-scripts/ValidateScript.sh
      timeout: 60
      runas: root
